project.name=opi3
project.version=1.0.0

src.main=src/main/java
src.resources=src/main/resources
src.webapp=src/main/webapp
src.test=src/test/java

build.dir=build/ant
classes.dir=${build.dir}/classes
test.classes.dir=${build.dir}/test-classes
dist.dir=${build.dir}/dist
reports.dir=${build.dir}/reports
tmp.dir=${build.dir}/tmp
history.dir=${build.dir}/history

lib.dir=lib
manifest.file=manifest/MANIFEST.MF
war.name=Lab3.war
war.file=${dist.dir}/${war.name}
webxml.file=${src.webapp}/WEB-INF/web.xml

javac.source=17
javac.target=17
encoding=UTF-8

test.report.dir=${reports.dir}/junit
test.report.xml=${test.report.dir}/TESTS-TestSuites.xml

xml.includes=**/*.xml

music.file=build-success.wav

scp.host=se.ifmo.ru
scp.port=2222
scp.user=s466300
scp.remote.dir=/home/studs/s466300/opi3
scp.keyfile=${user.home}/.ssh/helios

svn.report.path=svn-reports
svn.message=Add junit report from Ant build

#env.java.home=/Users/temanekrasov/Library/Java/JavaVirtualMachines/openjdk-23.0.2/Contents/Home
env.java.home=/Users/temanekrasov/Library/Java/JavaVirtualMachines/corretto-17.0.13/Contents/Home
env.server.home=/Users/temanekrasov/Downloads/wildfly-19.0.0.Final
env.jvm.args=-Xmx512m -Dfile.encoding=UTF-8
env.deploy.dir=${env.server.home}/standalone/deployments

team.revisions=4
team.zip=${dist.dir}/team-builds.zip

history.diff.file=${history.dir}/broken-revision.diff


sonar.scanner.executable=sonar-scanner
sonar.host.url=http://localhost:9000
sonar.projectKey=opi3
sonar.projectName=opi3
sonar.token=${env.SONAR_TOKEN}